### ISSUE TITLE
Sending message to a non-existing recepient doesn't return an error

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-ios-sdk#240]
Scenario:

- Send message from messenger to non existing SIP URI
- I never receive a 404 error code which I would expect

Analysing Restcomm logs shows that:

- Restcomm gets MESSAGE and seems to be forwarding it (to the LB I assume)
- Restcomm receives an answer from LB (404)
- Restcomm doesn't forward the 404 to messenger

Here are the Restcomm logs from the scenario:

https://gist.github.com/atsakiridis/1c1ecf5d3a54e0621937

**Comment by gvagenas** [comment]
@atsakiridis The Restcomm issue for this : https://github.com/Mobicents/RestComm/issues/442

**Comment by atsakiridis** [comment]
Just verified fix from @gvagenas
