### ISSUE TITLE
setRemoteDescriptionWithDelegate Error

### ISSUE THREAD

**Issue by toneyt** [Mobicents/restcomm-ios-sdk#77]
I get:

Failed to set session description. Error: Error Domain=RTCSDPError Code=-1 "The operation couldn’t be completed. (RTCSDPError error -1.)" UserInfo=0x175eb2f0 {error=SessionDescription is NULL.}

Even though the SDP seems to be ok (and not NULL).

**Comment by teo029** [comment]
Have you solved this?

**Comment by deruelle** [comment]
Yes it's solved and part of the last SDK release
